# Title of the page
title: "History of the Neuromarketing Industry"
# Your name
author: NTMC
# Show a link to LinkedIn in the header intro. Comment out to disable.
#linkedin: https://www.linkedin.com/in/guptaneil/
# Show a link at the top of your timeline to your main personal site
# Comment this out to disable
#personal_site:
#  url: https://neil.gg
#  title: neil.gg
# show today marker at end of timeline
#show_today: true

# Your timeline is split into periods (e.g., decades, childhood/teens/adult, "Before Timeliner"/"After Timeliner", etc)
# Each period has a list of events formatted as `- date: title`. If you don't want to have period dividers, leave out the name field.
periods:
  - name: Early Developments in Neuromarketing
  - events:
    - Pre-1980s: >-
        There existed an extensive history of interest in the idea behind neuromarketing.
        <br>
        <br>
        Although the field of neuromarketing is relatively new, the desire to gain insight into the minds of people is not.
        <br>
        <br>
        In 1913, Hug Munsterberg, the father of organizational psychology, was recorded as expressing interest in this potential field when he stated: 
        "Businessmen will eventually realize that customers are merely bundles of mental states and that the mind is a mechanism that we can affect with 
        the same exactitude with which we control a machine in a factory".
        <br>
        <br>
        Prior to the development of modern brain imaging technology, there was a long history of sensory neuroscience research in industry for product deveopment.
        <br>
        <br>
        However, it wasn't until the emergence of biomdeical imaging technology in the 1990s when it became possible to gain real insight from the neural 
        activity of the human brain.
    - 1980s-1990s: >-
        Gerald Zaltman, 'Mind of the Market Lab', used positron emission tomography (PET) and functional magnetic resonance imaging (fMRI) 
        to examine neural responses to advertisements and products.
        <br>
        <br>
        <b>Gerald Zaltman</b> develops the
        <a href="https://en.wikipedia.org/wiki/Zaltman_metaphor_elicitation_technique" target="_blank" rel="noopener">Zaltman metaphor elicitation technique (ZMET)</a>
        at Harvard Business School in the early 1990s.
        <br>
        <br>
        ZMET is a technique that prompts study participants to share a set of pictures that represent their thoughts and feelings about a particular 
        topic. The pictures that participants collect are thought to provide insight into their deeply held, often unconscious, thoughts and feelings.
        <br>
        <br>
        Zaltman - 'A lot goes on in our minds that we are not aware of. Most of what we say and do occurs below the level of awareness. That is why
        we need new techniques: to get at hidden knowledge - to get at what people dont know they know'.
    - 1999: "<b>Gemma Calvert</b> (Oxford) founds 'Neurosense', the first neuromarketing company."
    - 2000: "<b>Zaltman</b> & <b>Kosslyn</b> file a patent for neuroimaging as a means of validating if ads evoke mental response and if that can 
    predict behaviour."
    - 2002: >-
        <b>Ale Smidts</b> (Marketing Professor, Erasmus University) coins 'Neuromarketing'. The term was used to describe the adoption of neuroscientific 
        techniques by those in the marketing field.
        <br>
        <br>
        BrightHouse neurostrategies group (Emory) used fMRI to vet ads.
    - 2003: "<b>Ralph Nader</b> and 'Commerical Alert' slam Emory for allowing commercial use of MRI leading to an ongoing discussion of ethics in 
    neuromarketing."
    
  - name: Early meetings between Economists and Neurophysiologists
    events:
    - Late 1990s: >-
        Emergence of neuroeconomics
        <br>
        <br>
        Neuroeconomics emerged in the late 1990s/early 2000s largely due to brain imaging technology that allowed crossover between behaviour and 
        neurobiological inquiry.
        <br>
        <br>
        At that time, emerging evidence indicated that individuals were prone to making 'irrational choices' which contradicted classical economic 
        thinking and demanded explanation.
        <br>
        <br>
        <b>Daniel Kahneman</b>, a behavioural economist, differentiated two styles of processing calling them intuition (or system 1) and reasoning (system 2).
    - 1997: "Carnegie Mellon U (Camerer & Lowenstein)."
    - 2001: "Gruter Foundation for Law, Princeton University."
    - 2002: "<b>Kahneman</b> wins Nobel Prize in Economics for System 1/2."
    - 2005: "1st meeting of Society for Neuroeconomics, President <b>P. Glimcher</b>."
  - name: Emergence of Neuromarketing Firms 
    events: 
    - 1999: "Neurosense (Oxford)"
    - 2000: "BrightHouse (Emory)"
    - 2004: "FKF Applied Research (UCLA)"
    - 2005: "Neurofocus (Berkeley)"
    - 2006: "Innerscope Research (MIT)"
    - 2009: "Buyology (Martin Lindstrom)"
    - 2010: Neurensics (Amsterdam)"
    - 2008-2015: "<b>Nielsen</b> acquires Neurofocus (2008,2011) and Innerscope (2015)"
    - 2013: "NeuronsInc (Copenhagen University)"
